version: '3.6'
services:
  xxl-job:
    image: registry.cn-hangzhou.aliyuncs.com/kechangqing/frostmourne:0.4
    container_name: xxl-job
    environment:
      spring_datasource_url: jdbc:mysql://host.docker.internal:3306/xxl_job?Unicode=true&characterEncoding=UTF-8
      spring_datasource_username: root
      spring_datasource_password: example
      spring_mail_host: smtp.qq.com
      spring_mail_port: 25
      spring_mail_username: xxx@qq.com
      spring_mail_password: xxx
      xxl_job_accessToken:
      xxl_job_i18n:
    ports:
      - '10052:10052'
    expose:
      - '10052'
    networks:
      frostmourne_net:

    command: bash -c "/opt/frostmourne/start.sh xxl-job"

  frostmourne-spi:
    image: registry.cn-hangzhou.aliyuncs.com/kechangqing/frostmourne:0.4
    container_name: frostmourne-spi
    environment:
      email.smtp.host: smtp.qq.com
      email.smtp.port: 25
      email.smtp.auth: 'true'
      email.sender: xxx@qq.com
      email.sender.password: xxx
      dwz45.token: t8HGzRNv9TmvqUFICNoW3SaYNA1C9OAC
      wechat.corpid:
      wechat.agentid:
      wechat.secret:
    ports:
      - '10053:10053'
    expose:
      - '10053'
    networks:
      frostmourne_net:
    depends_on:
      - xxl-job
    command: bash -c "/opt/frostmourne/start.sh frostmourne-spi"

  frostmourne-monitor:
    image: registry.cn-hangzhou.aliyuncs.com/kechangqing/frostmourne:0.4
    container_name: frostmourne-monitor
    environment:
      datasource_frostmourne_url: jdbc:mysql://host.docker.internal:3306/frostmourne?useSSL=false&verifyServerCertificate=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
      datasource_frostmourne_username: root
      datasource_frostmourne_password: example
      xxljob_admin_addresses: http://xxl-job:10052/xxl-job-admin
      xxljob_executor_id: 2
      xxljob_executor_logpath: /opt/frostmourne/frostmourne-monitor/10054/log
      xxljob_executor_logretentiondays: 3
      xxljob_alarm_email: your_eamil@163.com
      frostmourne_spi_service: http://frostmourne-spi:10053
      frostmourne_monitor_address: http://localhost:10054
      initial_password:
      alarmlog_reserve_days: 30
      ldap_enabled: 'false'
      spring_ldap_urls:
      spring_ldap_username:
      spring_ldap_password:
      spring_ldap_base:
      spring_ldap_auth_searchFilter:
    ports:
      - '10054:10054'
      - '9999:9999'
    expose:
      - '10054'
      - '9999'
    depends_on:
      - frostmourne-spi
    networks:
      frostmourne_net:

    command: bash -c "/opt/frostmourne/start.sh frostmourne-monitor"

networks:
  frostmourne_net:
